export const motion = (type, options = {}) => ({ type, period: 9, phase: 0, ...options });
const floor = (id, x, z, w, d, top = 0) => ({ id, x, y: top - .6, z, w, h: .6, d, kind: 'floor', color: 'ivory' });
const exhibit = (id, name, x, y, z, w, h, d, program = null, kind = 'platform') => ({ id, name, x, y, z, w, h, d, program, kind, interactive: true, color: program ? 'orange' : 'teal' });
export const LEVELS = [
  {
    name: 'Please keep moving', wing: 'THE HALL OF INCONVENIENT BRIDGES', number: '01',
    intro: 'The bridge is perfectly safe. Unfortunately, it refuses to stay where you put your feet.',
    objective: 'Stop the bridge between the two landings. Walk to the exit.',
    spawn: { x: 9, y: 0, z: 17 }, exit: { x: 9, y: 0, z: 2.8 },
    floors: [floor('start', 9, 15.3, 5, 8.6), floor('end', 9, 4, 5, 6)],
    objects: [exhibit('bridge', 'Unreliable bridge', 3, -.5, 9, 3, .5, 4.4, motion('shuttle', { dx: 12, period: 11 }))],
    notes: [{ x: 10.6, y: 0, z: 3.3, text: 'Movement is not a thing an object does. It is a thing an object has.' }],
    hints: ['Click the orange bridge. Its movement goes into your hand; the bridge stays exactly where it is.', 'The striped landing is at the center. Wait until the bridge lines up with it, then take its movement.', 'If you stopped it too early, click the bridge to give the movement back. Try again when it reaches the middle.'],
  },
  {
    name: 'Heavy art', wing: 'THE DEPARTMENT OF ELEVATED OPINIONS', number: '02',
    intro: 'A sculpture spends all day going up and down. A floor would make much better use of the talent.',
    objective: 'Borrow the sculpture’s rise. Give it to the floor slab.',
    spawn: { x: 9, y: 0, z: 17 }, exit: { x: 9, y: 4, z: 3 },
    floors: [floor('start', 9, 15.5, 16, 9), floor('end', 9, 4.5, 12, 7, 4)],
    objects: [exhibit('bust', 'An elevated opinion', 3.5, .4, 15, 1.4, 1.7, 1.4, motion('lift', { dy: 4, phase: .12 }), 'sculpture'), exhibit('slab', 'Unambitious floor', 9, -.4, 9.6, 3.3, .4, 3.5)],
    notes: [{ x: 14, y: 4, z: 4, text: 'The sculpture has requested that we call this a promotion.' }],
    hints: ['Click the floating sculpture to take its up-and-down motion. Then click the empty slab.', 'The slab will become a lift. Walk onto it when it meets the lower floor, and let it carry you.', 'At the top, walk forward onto the balcony. You do not need to jump.'],
  },
  {
    name: 'A useful absence', wing: 'ARCHITECTURE WITHOUT ARCHITECTS', number: '03',
    intro: 'Take a movement, leave a landing. One theft can solve two problems.',
    objective: 'Leave the column high. Use its motion to raise the slab.',
    spawn: { x: 9, y: 0, z: 17 }, exit: { x: 9, y: 4.8, z: 2.5 },
    floors: [floor('start', 9, 16.5, 6, 7), floor('end', 9, 3, 6, 6, 4.8)],
    objects: [exhibit('column', 'The missing landing', 9, -.5, 7.5, 3.3, .5, 3, motion('lift', { dy: 4.8, period: 10 })), exhibit('slab', 'A floor with potential', 9, -.5, 11, 3.3, .5, 4)],
    notes: [{ x: 10.8, y: 4.8, z: 3, text: 'The empty space under an idea is sometimes the important part.' }],
    hints: ['The moving column must become a fixed landing at the height of the exit.', 'Wait until the column is at its highest point, then take its movement and put it into the lower slab.', 'Ride the slab to the top, cross the frozen column, and walk to the exit. Undo is free if your timing was early.'],
  },
  {
    name: 'Security ballet', wing: 'PLEASE DO NOT TOUCH THE ALARM', number: '04',
    intro: 'Security spent a fortune making its scanner move. You have a more useful place for that movement.',
    objective: 'Leave the scanner safely to the left. Turn the slab into a ferry.',
    spawn: { x: 3, y: 0, z: 15 }, exit: { x: 15, y: 0, z: 5.5 },
    floors: [floor('start', 3, 10, 6, 17), floor('end', 15, 10, 6, 17)],
    objects: [exhibit('scanner', 'Very expensive security', 1, .05, 2.5, .8, 2, .8, motion('shuttle', { dx: 8, period: 12, phase: .08 }), 'scanner'), exhibit('ferry', 'Budget transport', 7, -.45, 11, 2.5, .45, 3.2)],
    notes: [{ x: 16, y: 0, z: 16.5, text: 'A security system is just public transport with a hostile attitude.' }],
    hints: ['The scanner’s red line detects you. Taking its movement also freezes that line.', 'Wait until the scanner is far left, behind your starting position. Steal its shuttle and give it to the ferry.', 'Board the ferry at the left bank. Stay on it until it reaches the other side. If the frozen beam blocks you, undo the theft.'],
  },
  {
    name: 'The long way around', wing: 'THE COLLECTION OF UNNECESSARY ORBITS', number: '05',
    intro: 'The shortest distance between two points has been removed for conservation.',
    objective: 'Give the orbit to the disc. Ride the long way around.',
    spawn: { x: 14, y: 0, z: 17.4 }, exit: { x: 4, y: 0, z: 3 },
    floors: [floor('start', 14, 17.5, 4, 5), floor('end', 4, 8, 4, 12), floor('island', 9, 8, 2.5, 2.5)],
    objects: [exhibit('orbit', 'An unnecessary orbit', 14, 1.5, 17, .9, 1.3, .9, motion('orbit', { radius: 5, period: 15 }), 'sculpture'), exhibit('disc', 'A very patient disc', 14, -.45, 14, 2.7, .45, 2.7)],
    notes: [{ x: 9, y: 0, z: 8, text: 'Taking the long way is still a way of arriving.' }],
    hints: ['Take the circling sculpture’s orbit. Place it in the square disc at the edge of your landing.', 'Board when the disc returns to the starting edge. Its orbit reaches the far landing on the left.', 'The small middle island holds a catalogue note. It is optional; your exit is on the far-left landing.'],
  },
  {
    name: 'Everything goes somewhere', wing: 'THE LAW OF CONSERVATION OF TROUBLE', number: '06',
    intro: 'You have one hand. The building has several opinions about where its floors should be.',
    objective: 'Make a route at the upper height. Find somewhere safe for spare motion.',
    spawn: { x: 9, y: 0, z: 17 }, exit: { x: 9, y: 4, z: 2.5 },
    floors: [floor('start', 9, 17, 10, 6), floor('end', 9, 3, 5, 6, 4)],
    objects: [exhibit('first', 'First disagreement', 9, -.5, 12, 3.4, .5, 4, motion('lift', { dy: 4, period: 10, phase: .08 })), exhibit('second', 'Second disagreement', 9, -.5, 8, 3.4, .5, 4, motion('lift', { dy: 4, period: 10, phase: .58 })), exhibit('spare', 'Somewhere else', 13.5, 0, 17, 1.3, 1.2, 1.3, null, 'sculpture')],
    notes: [{ x: 10.5, y: 4, z: 3.5, text: 'We cannot abolish inconvenience. We can, however, relocate it.' }],
    hints: ['Clicking a moving object while carrying motion exchanges the two. You never destroy a movement.', 'Ride the first floor upward and stop it at the top. Store its motion in the spare sculpture on the starting landing.', 'Now your hand is empty. Stop the second floor at the same height, then walk across both floors to the exit.'],
  },
  {
    name: 'The curator’s cage', wing: 'THE LAST THING THAT MUST NOT BE STOLEN', number: '07',
    intro: 'Behind the cage: the little movement that keeps the entire museum going.',
    objective: 'Stop the escape bridge. Move the cage. Steal the little sun.',
    spawn: { x: 9, y: 0, z: 17.5 }, exit: { x: 9, y: 0, z: 2 },
    floors: [floor('start', 9, 13, 16, 12), floor('end', 9, 2, 4.5, 4)],
    objects: [exhibit('bridge', 'Your way out', 3, -.45, 5.5, 3.2, .45, 3.4, motion('shuttle', { dx: 12, period: 12 })), exhibit('cage', 'The curator’s certainty', 9, 0, 11.5, 4, 3.5, 4, null, 'cage'), { ...exhibit('sun', 'The little sun', 9, 1.5, 11.5, .5, .5, .5, motion('orbit', { radius: .35, period: 6, prize: true }), 'sun'), solid: false, prize: true }],
    notes: [{ x: 3, y: 0, z: 15, text: 'The curator mistook possession for preservation.' }],
    hints: ['First freeze the bridge in the center, lined up with the exit. Its motion will be your tool for opening the cage.', 'Put the bridge’s shuttle into the cage. The entire cage will slide away. Walk up to the little sun.', 'Take the sun’s motion when you are close to it. Everything stops. Carry it across your frozen bridge to the exit.'],
  },
  {
    name: 'An unauthorized dawn', wing: 'OUTSIDE THE COLLECTION', number: '08',
    intro: 'One last thing. It has been waiting a very long time to be a bird.',
    objective: 'Give the stolen motion to the paper bird.',
    spawn: { x: 9, y: 0, z: 15 }, exit: null,
    floors: [floor('outside', 9, 10, 13, 18)],
    objects: [{ ...exhibit('bird', 'Something that should be free', 9, 1.05, 8, .9, .5, .9, null, 'bird'), solid: false }],
    notes: [], hints: ['You brought the museum’s last movement outside.', 'Walk up to the paper bird. Click it to give it the movement in your hand.', 'The motion was never meant to belong to a museum.'],
  },
];
